// app/api/llm-analysis/route.ts
import { NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import fs from "fs/promises";
import path from "path";

// Initialize Gemini
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");

// The System Instruction provided
const TASK_1_SYSTEM_PROMPT = `
You are an expert in land-use change interpretation. You must analyze land-use transitions using only the provided data.

Task 1. Summarize Land-Use Change Using the Four CSV Files

Summarize land-use change patterns for the reclassified classes:
1 = Water, 2 = Developed, 3 = Forest, 4 = Shrub, 5 = Herbaceous, 6 = Nonvascular, 7 = Sparse Vegetation.

Produce a concise summary of overall patterns and major transitions. In the summary, address who are the Active Gainer, Active Loser, as well as who gain most (the primary “sink” for the land user transitions), who lost most.

General Rules:
- No hallucination. Do not infer patterns not supported by data.
- Evidence-based only.
- Focus strictly on reclassified land-use results.
`;

// Helper to simulate reading CSV data. 
// IN PRODUCTION: You would read these files from the folder generated by your Analysis step.
async function getAnalysisData(siteId: string) {
  // TODO: Replace this with actual fs.readFile logic pointing to where your FastAPI/Analysis saved the CSVs.
  // For now, we return mock string data matching the file names so the LLM has something to process.
  
  const transitionTable = `
FROM_CLASS,TO_CLASS,PIXEL_COUNT,PERCENTAGE
Forest,Developed,1200,5.2
Herbaceous,Developed,800,3.1
Forest,Herbaceous,450,1.9
Developed,Developed,50000,99.0
  `;

  const rankedTable = `
RANK,TRANSITION,INTENSITY_VALUE
1,Forest to Developed,0.85
2,Herbaceous to Developed,0.72
  `;

  const chiSquare = `
TRANSITION,OBSERVED,EXPECTED,CHI_SQUARE,SIGNIFICANT
Forest->Developed,1200,800,200.0,YES
  `;

  const intensity = `
CATEGORY,GAIN_INTENSITY,LOSS_INTENSITY
Developed,2.5,0.1
Forest,0.2,1.8
  `;

  return `
=== FILE: NLCD_Transition_Tables.csv ===
${transitionTable}

=== FILE: NLCD_Normalized_Ranked.csv ===
${rankedTable}

=== FILE: NLCD_ChiSquare_Results.csv ===
${chiSquare}

=== FILE: NLCD_Intensity_Analysis.csv ===
${intensity}
  `;
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { siteId, year1, year2 } = body;

    if (!process.env.GEMINI_API_KEY) {
      return NextResponse.json({ error: "Gemini API Key not configured" }, { status: 500 });
    }

    // 1. Fetch the data strings
    const csvContext = await getAnalysisData(siteId);

    // 2. Initialize Model
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    // 3. Construct the full user prompt
    const userPrompt = `
Analyze the Land Use Change for Site: ${siteId} (${year1} to ${year2}).

DATA INPUTS:
${csvContext}

Please perform Task 1 as defined in your system instructions.
    `;

    // 4. Call LLM
    const result = await model.generateContent({
      contents: [
        { role: "user", parts: [{ text: TASK_1_SYSTEM_PROMPT + "\n\n" + userPrompt }] }
      ]
    });

    const response = result.response;
    const text = response.text();

    return NextResponse.json({ result: text });

  } catch (error: any) {
    console.error("LLM Analysis Error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to analyze data." },
      { status: 500 }
    );
  }
}